[package]
name = "terani"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
crossterm = "0.27.0"
rand = "0.8.5"
textwrap = "0.16.1"
